create_clock -name core_clk -period 100.0 [get_ports clk]
set_clock_uncertainty 1.0 [get_clocks core_clk]
set_input_delay 5.0 -clock core_clk [get_ports {start act_we act_address* act_data*}]
set_output_delay 5.0 -clock core_clk [all_outputs]
set_false_path -from [get_ports reset_n]
